version: '3.8'

services:
  app:
    image: arm64v8/node:15.11.0-buster
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  db:
    image: arm64v8/postgres:13.2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    network_mode: service:app

  # db-testing:
  #   image: arm64v8/postgres:13.2
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: password
  #   command: -p 5433
  #   network_mode: service:app
    
